#!/bin/bash

# Check if the script is run as root
if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root"
  exit 1
fi

# Get the current directory
current_dir=$(pwd)

# Get the project name from the command line argument
project_name=$1

# Create the alias line
alias_line="alias $project_name='cd $current_dir && code .'"

# Append the alias line to ~/.bash_aliases
echo "$alias_line" >>~/.bash_aliases

# Source ~/.bash_aliases to make the changes take effect
source ~/.bash_aliases
