#!/bin/bash

if [[ $1 == "-s" ]]; then
  cd /opt/lampp && sudo ./xampp stop && cd -
elif [[ $1 == "-r" ]]; then
  cd /opt/lampp && sudo ./xampp reload && cd -
else
  cd /opt/lampp && sudo ./xampp start && cd -
fi
